import 'dart:ui';
import 'package:flutter/material.dart';
import '../../core/app_export.dart';
import '../core/utils/size_utils.dart';

String _appTheme = "primary";

/// Helper class for managing themes and colors.
class ThemeHelper {
  // A map of custom color themes supported by the app
  Map<String, PrimaryColors> _supportedCustomColor = {
    'primary': PrimaryColors()
  };

// A map of color schemes supported by the app
  Map<String, ColorScheme> _supportedColorScheme = {
    'primary': ColorSchemes.primaryColorScheme
  };

  /// Changes the app theme to [_newTheme].
  void changeTheme(String _newTheme) {
    _appTheme = _newTheme;
  }

  /// Returns the primary colors for the current theme.
  PrimaryColors _getThemeColors() {
    //throw exception to notify given theme is not found or not generated by the generator
    if (!_supportedCustomColor.containsKey(_appTheme)) {
      throw Exception(
          "$_appTheme is not found.Make sure you have added this theme class in JSON Try running flutter pub run build_runner");
    }
    //return theme from map

    return _supportedCustomColor[_appTheme] ?? PrimaryColors();
  }

  /// Returns the current theme data.
  ThemeData _getThemeData() {
    //throw exception to notify given theme is not found or not generated by the generator
    if (!_supportedColorScheme.containsKey(_appTheme)) {
      throw Exception(
          "$_appTheme is not found.Make sure you have added this theme class in JSON Try running flutter pub run build_runner");
    }
    //return theme from map

    var colorScheme =
        _supportedColorScheme[_appTheme] ?? ColorSchemes.primaryColorScheme;
    return ThemeData(
      visualDensity: VisualDensity.standard,
      colorScheme: colorScheme,
      textTheme: TextThemes.textTheme(colorScheme),
      elevatedButtonTheme: ElevatedButtonThemeData(
        style: ElevatedButton.styleFrom(
          backgroundColor: colorScheme.primary,
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(
              8,
            ),
          ),
          shadowColor: appTheme.blueGray900.withOpacity(0.15),
          elevation: 2,
          visualDensity: const VisualDensity(
            vertical: -4,
            horizontal: -4,
          ),
          padding: EdgeInsets.zero,
        ),
      ),
      outlinedButtonTheme: OutlinedButtonThemeData(
        style: OutlinedButton.styleFrom(
          backgroundColor: Color(0XFFFFFFFF),
          shape: RoundedRectangleBorder(
            side: BorderSide(
              width: 2,
            ),
            borderRadius: BorderRadius.circular(
              8,
            ),
          ),
          visualDensity: const VisualDensity(
            vertical: -4,
            horizontal: -4,
          ),
          padding: EdgeInsets.zero,
        ),
      ),
      dividerTheme: DividerThemeData(
        thickness: 2,
        space: 2,
      ),
    );
  }

  /// Returns the primary colors for the current theme.
  PrimaryColors themeColor() => _getThemeColors();

  /// Returns the current theme data.
  ThemeData themeData() => _getThemeData();
}

/// Class containing the supported text theme styles.
class TextThemes {
  static TextTheme textTheme(ColorScheme colorScheme) => TextTheme(
        bodyLarge: TextStyle(
          color: appTheme.blueGray300,
          fontSize: getFontSize(
            18,
          ),
          fontFamily: 'Inter',
          fontWeight: FontWeight.w400,
        ),
        bodyMedium: TextStyle(
          color: appTheme.gray900,
          fontSize: getFontSize(
            13,
          ),
          fontFamily: 'Work Sans',
          fontWeight: FontWeight.w400,
        ),
        bodySmall: TextStyle(
          color: appTheme.orange300,
          fontSize: getFontSize(
            11,
          ),
          fontFamily: 'Inter',
          fontWeight: FontWeight.w400,
        ),
        displaySmall: TextStyle(
          color: colorScheme.onPrimaryContainer.withOpacity(1),
          fontSize: getFontSize(
            36,
          ),
          fontFamily: 'Inter',
          fontWeight: FontWeight.w700,
        ),
        headlineMedium: TextStyle(
          color: colorScheme.onPrimaryContainer.withOpacity(1),
          fontSize: getFontSize(
            28,
          ),
          fontFamily: 'Inter',
          fontWeight: FontWeight.w700,
        ),
        labelLarge: TextStyle(
          color: appTheme.black900,
          fontSize: getFontSize(
            12,
          ),
          fontFamily: 'Poppins',
          fontWeight: FontWeight.w700,
        ),
        labelMedium: TextStyle(
          color: appTheme.blueGray900,
          fontSize: getFontSize(
            11,
          ),
          fontFamily: 'Inter',
          fontWeight: FontWeight.w500,
        ),
        titleMedium: TextStyle(
          color: appTheme.teal300,
          fontSize: getFontSize(
            16,
          ),
          fontFamily: 'Inter',
          fontWeight: FontWeight.w600,
        ),
        titleSmall: TextStyle(
          color: appTheme.gray90002.withOpacity(0.49),
          fontSize: getFontSize(
            14,
          ),
          fontFamily: 'Inter',
          fontWeight: FontWeight.w700,
        ),
      );
}

/// Class containing the supported color schemes.
class ColorSchemes {
  static final primaryColorScheme = ColorScheme.light(
    // Primary colors
    primary: Color(0XFF234E5C),
    primaryContainer: Color(0XFFD8EFF5),
    secondary: Color(0XFFD8EFF5),
    secondaryContainer: Color(0XFF234E5C),
    tertiary: Color(0XFFD8EFF5),
    tertiaryContainer: Color(0XFF234E5C),

    // Background colors
    background: Color(0XFFD8EFF5),

    // Surface colors
    surface: Color(0XFFD8EFF5),
    surfaceTint: Color(0XBA070429),
    surfaceVariant: Color(0XFF234E5C),

    // Error colors
    error: Color(0XBA070429),
    errorContainer: Color(0X26133039),
    onError: Color(0XFF234E5C),
    onErrorContainer: Color(0XFFD8EFF5),

    // On colors(text colors)
    onBackground: Color(0X26133039),
    onInverseSurface: Color(0XFF234E5C),
    onPrimary: Color(0XBA070429),
    onPrimaryContainer: Color(0X26133039),
    onSecondary: Color(0X26133039),
    onSecondaryContainer: Color(0XBA070429),
    onTertiary: Color(0X26133039),
    onTertiaryContainer: Color(0XBA070429),

    // Other colors
    outline: Color(0XBA070429),
    outlineVariant: Color(0XFFD8EFF5),
    scrim: Color(0XFFD8EFF5),
    shadow: Color(0XBA070429),

    // Inverse colors
    inversePrimary: Color(0XFFD8EFF5),
    inverseSurface: Color(0XBA070429),

    // Pending colors
    onSurface: Color(0X26133039),
    onSurfaceVariant: Color(0XBA070429),
  );
}

/// Class containing custom colors for a primary theme.
class PrimaryColors {
  // Black
  Color get black900 => Color(0XFF000000);

  // BlueGray
  Color get blueGray300 => Color(0XFF7EA9BA);
  Color get blueGray400 => Color(0XFF888888);
  Color get blueGray900 => Color(0XFF142B38);

  // Cyan
  Color get cyan800 => Color(0XFF286F8C);

  // DeepOrange
  Color get deepOrange300 => Color(0XFFEF9453);
  Color get deepOrange80077 => Color(0X77D23909);

  // Gray
  Color get gray100 => Color(0XFFF0FBFB);
  Color get gray400 => Color(0XFFC4C4C4);
  Color get gray40019 => Color(0X19B3B3B3);
  Color get gray50 => Color(0XFFF7FAFC);
  Color get gray600 => Color(0XFF707070);
  Color get gray70054 => Color(0X54615C5C);
  Color get gray900 => Color(0XFF1E232C);
  Color get gray90001 => Color(0XFF141619);
  Color get gray90002 => Color(0XFF121212);

  // GrayFc
  Color get gray100Fc => Color(0XFCF3F3F7);

  // Indigo
  Color get indigo200 => Color(0XFF95BECF);

  // Orange
  Color get orange300 => Color(0XFFF3AA60);

  // Red
  Color get red300 => Color(0XFFEE6363);
  Color get red400 => Color(0XFFEF6358);

  // Redc
  Color get red4004c => Color(0X4CEF6262);

  // Teal
  Color get teal200 => Color(0XFF84CADC);
  Color get teal300 => Color(0XFF4AAAC6);
  Color get teal400 => Color(0XFF2E8DAC);

  // White
  Color get whiteA700 => Color(0XFFFFFFFF);

  // Yellow
  Color get yellow900 => Color(0XFFCE9911);
}

PrimaryColors get appTheme => ThemeHelper().themeColor();
ThemeData get theme => ThemeHelper().themeData();
